# Site settings
email: your-email@domain.com
brand: Lars Kristian Gjelstad
headline: Student, Computer Engineering
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nettsiden.com" # the base hostname & protocol for your site
copyright: 2018 Lars Kristian Gjelstad, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Contacts
email: lkgjelst@stud.ntnu.no
linkedin: https://www.linkedin.com/in/largje/

# Tracking
googleAnalitycsID: UA-83933844-1

